import CheckoutForm from "@/components/checkout-form";
import { getAll, getById } from "@/app/actions/entity";
import { Entity } from "@/lib/enum/entity";
import CheckoutDetails from "@/components/checkout-details";
import { capitalize } from "@/lib/utils";
import { createLogger } from "@/lib/logger";
import { TPaymentOption } from "@/components/payment-pill";
import InfoMessage from "@/components/info-message";
import CheckoutCard from "@/components/checkout-card";

export default async function CheckoutPage({
  params,
}: {
  params: Promise<{ checkoutId: string }>;
}) {
  const { checkoutId } = await params;

  const checkout = await getById(Entity.CHECKOUT, checkoutId);

  // Create logger with session context
  let logger = createLogger({
    sessionId: checkoutId,
    leadId: checkout?.lead?.lead_id,
  });

  if (!checkout) {
    logger.error("Checkout not found");
    return <div>No se encontró el checkout</div>;
  }

  if (!checkout.lead?.carrera?.carrera_id) {
    logger.error("Career not found");
    // TODO: Show ask form for career
    return <div>No se encontró la carrera</div>;
  }
  if (!checkout.lead?.pais?.pais_id) {
    logger.error("Country not found");
    // TODO: Show ask form for country
    return <div>No se encontró el país</div>;
  }

  // Update logger with confirmed leadId
  logger = logger.withContext({
    leadId: checkout.lead?.lead_id,
  });

  const [careers, discounts] = await Promise.all([
    getAll(Entity.CAREER, {
      limit: "1000",
    }).then(
      ({ data }) =>
        data?.sort((a, b) =>
          a.carrera_nombre.localeCompare(b.carrera_nombre)
        ) || ([] as TCareer[])
    ),
    getAll(Entity.DISCOUNT, {
      where: JSON.stringify({
        checkout: true,
      }),
    }),
  ]);

  const career = careers.find(
    (career) => career.carrera_id === checkout.lead?.carrera?.carrera_id
  );

  const cost = await getAll(Entity.COST, {
    where: JSON.stringify({
      pais: {
        pais_id: checkout.lead?.pais?.pais_id,
      },
      cuenta: {
        cuenta_id: checkout.lead?.carrera?.cuenta?.cuenta_id,
      },
    }),
    limit: "1",
  }).then(({ data }) => data?.[0] || null);
  const installmentCost =
    (cost?.costo_carrera ?? 0) / (career?.cuenta?.cuenta_cantidad_cuotas ?? 1);

  // Log checkout information
  logger.info("=== CHECKOUT INFORMATION ===");
  logger.info("Checkout ID:", checkout.checkout_id);
  logger.info("Status:", checkout.checkout_status);
  logger.info("Created At:", checkout.created_at);
  logger.info("Updated At:", checkout.updated_at);
  logger.info("Expires At:", checkout.expires_at);
  logger.info("Payment Method:", checkout.payment_method);
  logger.info("Payment Link:", checkout.payment_link);
  logger.info("Selected Plan Type:", checkout.selected_plan_type);
  logger.info("Selected Fecha Inicio:", checkout.selected_fecha_inicio);
  logger.info("Owner Email:", checkout.owner_email);
  logger.info("Agent Name:", checkout.agent_name);
  logger.info("Generated By Type:", checkout.generated_by_type);
  logger.info("Paid At:", checkout.paid_at);

  // Log lead information
  logger.info("=== LEAD INFORMATION ===");
  logger.info("Lead ID:", checkout.lead?.lead_id);
  logger.info("Name:", checkout.lead?.nombre);
  logger.info("Email:", checkout.lead?.email);
  logger.info("Phone:", checkout.lead?.telefono);
  logger.info("Phone LADA:", checkout.lead?.telefono_lada);
  logger.info("University Email:", checkout.lead?.correo_universitario);
  logger.info("Country:", checkout.lead?.pais?.pais_nombre);
  logger.info("Country ID:", checkout.lead?.pais?.pais_id);
  logger.info("Country Currency:", checkout.lead?.pais?.pais_moneda);
  logger.info("Status:", checkout.lead?.status?.status_nombre);
  logger.info("Source:", checkout.lead?.source?.source_nombre);
  logger.info("Fecha Promesa Pago:", checkout.lead?.fecha_promesa_pago);
  logger.info("Created At:", checkout.lead?.timestamp_creation);

  // Log career information
  logger.info("=== CAREER INFORMATION ===");
  if (career) {
    logger.info("Career ID:", career.carrera_id);
    logger.info("Career Name:", career.carrera_nombre);
    logger.info("Career Code:", career.carrera_codigo);
    logger.info("Career Active:", career.carrera_activo);
    logger.info("Account ID:", career.cuenta?.cuenta_id);
    logger.info(
      "Number of Installments:",
      career.cuenta?.cuenta_cantidad_cuotas
    );
    logger.info("Account Active:", career.cuenta?.cuenta_activo);
  } else {
    logger.error("Career not found");
  }

  // Log cost information
  logger.info("=== COST INFORMATION ===");
  if (cost) {
    logger.info("Cost ID:", cost.costo_id);
    logger.info("Cost Active:", cost.costo_activo);
    logger.info("Installment Cost:", installmentCost);
    logger.info(
      "Number of Installments:",
      career?.cuenta?.cuenta_cantidad_cuotas ?? "N/A"
    );
    logger.info("Total Career Cost:", cost.costo_carrera);
  } else {
    logger.error("Cost not found");
  }
  logger.info("================================\n");

  const paymentOptions: TPaymentOption[] = discounts.data
    .map((discount): TPaymentOption => {
      const numberOfInstallments = Number(
        discount.descuento_cuotas ?? career?.cuenta?.cuenta_cantidad_cuotas ?? 1
      );
      const originalPrice = installmentCost * numberOfInstallments;
      const finalPrice =
        originalPrice * (1 - Number(discount.descuento_porcentaje ?? 0));
      const installmentPrice = finalPrice / numberOfInstallments;
      return {
        id: discount.descuento_id,
        label: capitalize(discount.descuento_nombre),
        subtitle:
          Number(discount.descuento_porcentaje) > 0
            ? `${Number(discount.descuento_porcentaje) * 100}% de descuento`
            : "Inscripción inmediata",
        discount_percentage: Number(discount.descuento_porcentaje ?? 0),
        original_price: originalPrice,
        // Best option is anual plan
        bestOption: discount.descuento_nombre.toLowerCase().includes("anual"),
        final_price: finalPrice,
        installment_price: installmentPrice,
        numberOfInstallments: numberOfInstallments,
      };
    })
    .sort((a, b) => a.final_price - b.final_price);

  if (
    checkout.checkout_status === "payment_generated" ||
    checkout.checkout_status === "paid"
  ) {
    return (
      <CheckoutCard>
        <CheckoutDetails
          checkout={checkout}
          selectedPaymentOption={paymentOptions.find(
            (option) => option.id === checkout.selected_plan_type
          )}
        />
      </CheckoutCard>
    );
  }

  return (
    <CheckoutForm
      careers={careers}
      discounts={discounts.data}
      checkout={checkout}
      paymentOptions={paymentOptions}
    />
  );
}
